### ISSUE TITLE
[Bug] 下载路径在 mac 中识别错误

### ISSUE THREAD

**Issue by JasonLamv-t** [moreant/mpcb#2]
#### Describe the bug
<img width="500" alt="image" src="https://user-images.githubusercontent.com/39087996/221143285-31969a7c-aa42-4ae5-858f-2d19c3e43e3a.png">
应该是path没有处理好

**Comment by JasonLamv-t** [comment]
Already fix in #3

**Comment by moreant** [comment]
very thank
